version: '3.9'

services:
  app_development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest_with_redis_development
    restart: always
    env_file:
      - .env.development
    volumes:
      - .:/usr/src/app/dev
      - /usr/src/app/dev/node_modules
    ports:
      - '3066:3001'
    command: npm run dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.4
    container_name: nest_redis_db
    restart: always
    env_file:
      - .env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    environment:
      - .env.redis

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
