version: '3.9'

services:
  app_production:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nest_with_redis_production
    restart: always
    env_file:
      - .env.production
    volumes:
      - .:/app
    ports:
      - '3067:3002'
    depends_on:
      - db

  db:
    image: postgres:16.4
    container_name: nest_redis_db
    restart: always
    env_file:
      - .env.db 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
    driver: local
